extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - jest
rules:
  no-shadow: off
  '@typescript-eslint/no-shadow':
    - error
  no-use-before-define: off
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  react/react-in-jsx-scope: off
  '@typescript-eslint/no-unused-vars':
    - warn
  react/no-unescaped-entities: 
    - error
    - forbid:
      - ">"
      - "}"

env:
  browser: true
  jest/globals: true
settings:
  react:
    pragma: React
    version: detect
